### ISSUE TITLE
Ambari-Slider-View: Custom property doesn't accept new line

### ISSUE THREAD

**Issue by sanjay990** [prestodb/presto-yarn#34]
For e.g. tried to add custom property site.global.additional_config_properties
": "task.max-worker-threads=5\ndistributed-joins-enabled=true"

Tried giving the value in double quotes, single quotes or without quotes. Ambari doesn't understand "\n" and takes this a one value.

**Comment by petroav** [comment]
Can you not specify the second property as another custom property? Or are you just trying to stress test the system by providing funky input?

**Comment by sanjay990** [comment]
The input is as per the README document. I assume as per current implementation the key is "site.global.additional_config_properties", as that's the file name and I can't use the same key twice.

**Comment by petroav** [comment]
I see; then it makes sense to string together a couple of properties this way and if it doesn't work and this example is from the README then it's probably a legit bug.

**Comment by anusudarsan** [comment]
yup, this is a bug  (though it works for manual slider installation). We need to figure out a better way to add additional custom properties to Presto config files via Ambari
