### ISSUE TITLE
How slider require a new component instance when one of the components was fail? 

### ISSUE THREAD

**Issue by FanTn** [prestodb/presto-yarn#40]
Hi : 
    My presto cluster have 4 component instances (1 coordinator,3 workers), when I shut down a NodeManager node which WORKER component is running,  the presto component instance also stop.
How slider require a new component instance when one of the components was fail? 
    Thanks.

**Comment by kokosing** [comment]
I am not sure if I understand your question correctly. Slider runs additional component appmaster which monitors which component are working and which failed, when one fails it allocates a new equivalent component.

If you have 4 nodes in the cluster and 4 components, and you stop one NM then whole application will fail as appmaster will be unable to allocate a new component on a node without any presto component. Allocating two presto components on the same node is unsupported and causes fail.

**Comment by FanTn** [comment]
I stop one NodeManager, the whole application will not fail, the container which run on the NM will fail.

Slider Agent information:

```
http:// http://node87:1025
classpath:org.apache.slider.client.rest http://node87:1025
classpath:org.apache.slider.management http://node87:1025/ws/v1/slider/mgmt
classpath:org.apache.slider.publisher http://node87:1025/ws/v1/slider/publisher
classpath:org.apache.slider.registry http://node87:1025/ws/v1/slider/registry
classpath:org.apache.slider.publisher.configurations http://node87:1025/ws/v1/slider/publisher/slider
classpath:org.apache.slider.publisher.exports http://node87:1025/ws/v1/slider/publisher/exports
COORDINATOR Host(s)/Container(s): [node85/container_1450665217523_0003_02_000003]
slider-appmaster Host(s)/Container(s): [node87/container_1450665217523_0003_02_000001]
WORKER Host(s)/Container(s): [node91/container_1450665217523_0003_02_000006, node94/container_1450665217523_0003_02_000004, node93/container_1450665217523_0003_02_000002]
```

node91 jps info:

```
[hadoop@node91 ~]$ jps
25307 PrestoServer
45805 Jps
18829 DataNode
24271 NodeManager
```

and I stop node91 NM:

```
[hadoop@node91 ~]$ yarn-daemon.sh stop nodemanager
stopping nodemanager
[hadoop@node91 ~]$ jps
46051 Jps
18829 DataNode
```

then Slider Agent information :

```
http:// http://node87:1025
classpath:org.apache.slider.client.rest http://node87:1025
classpath:org.apache.slider.management http://node87:1025/ws/v1/slider/mgmt
classpath:org.apache.slider.publisher http://node87:1025/ws/v1/slider/publisher
classpath:org.apache.slider.registry http://node87:1025/ws/v1/slider/registry
classpath:org.apache.slider.publisher.configurations http://node87:1025/ws/v1/slider/publisher/slider
classpath:org.apache.slider.publisher.exports http://node87:1025/ws/v1/slider/publisher/exports
COORDINATOR Host(s)/Container(s): [node85/container_1450665217523_0003_02_000003]
slider-appmaster Host(s)/Container(s): [node87/container_1450665217523_0003_02_000001]
WORKER Host(s)/Container(s): [node94/container_1450665217523_0003_02_000004, node93/container_1450665217523_0003_02_000002]
```

Slider do not allocates a new component.

**Comment by anusudarsan** [comment]
@FanTn The behavior you see is expected. The status of the application on the YARN WebUI will show "Awaiting 1 containers" in this case. Unless the cluster has enough additional nodes  (and resources) to allocate the pending component it will not allocate the third component. In this case, to allocate the new component you will have to either 1) add a new nodeManager node or 2) restart node91 NM. 

But the 2) case wont work with strict placement policy (  "yarn.component.placement.policy": "1",
no escalation takes place here). You will probably have to set the placement policy to value '2' (See http://slider.incubator.apache.org/docs/configuration/resources.html#placement-policies-and-escalation).

**Comment by FanTn** [comment]
@anusudarsan  Thanks. I set the "yarn.component.placement.policy" to value "2", Yarn will allocate a new components.
