### ISSUE TITLE
Create etc/log.properties to change log level

### ISSUE THREAD

**Issue by gneets** [prestodb/presto-yarn#47]
I'm getting AccessDeniedException with hive sentry authorization in my CDH cluster and the INFO/ERROR logs are not very helpful in excavating the reason. Not sure if debug logs would help much, but I don't see the log.properties under etc/ as described [here](https://prestodb.io/docs/current/installation/deployment.html#log-levels). It would be helpful to be able to change presto's log levels through appConfig.json.

**Comment by kokosing** [comment]
@gneets We will try to include this in the road map for future releases. Thanks for posting this issue!

**Comment by kokosing** [comment]
Closed by #66
