### ISSUE TITLE
Outstanding requests never get fulfilled

### ISSUE THREAD

**Issue by tglstory** [prestodb/presto-yarn#51]
1) is the only way to stop/re-run a cluster to destroy/create? When you stop and start using slider, the restarted instance is just filled with outstanding request that never get fulfilled.
2) Even when creating a new cluster, some workers fail to come up and outstanding containers increase by the same amount. Same as above, the outstanding container requests never get fulfilled. I'm pretty sure this is a bug with slider, but this is causing a lot of trouble for us.

**Comment by tglstory** [comment]
FYI 
appConfig

```
{
  "schema": "http://example.org/specification/v2.0.0",
  "metadata": {
  },
  "global": {
    "site.global.app_user": "hive",
    "site.global.user_group": "hive",
    "site.global.app_name": "presto-server-0.147",
    "site.global.data_dir": "/data/appdata/presto/data",
    "site.globa.config_dir": "/data/appdate/presto/etc",
    "site.global.singlenode": "false",
    "site.global.coordinator_host": "${COORDINATOR_HOST}",
    "site.global.presto_query_max_memory": "360GB",
    "site.global.presto_query_max_memory_per_node": "12GB",
    "site.global.presto_server_port": "7777",
    "site.global.app_pkg_plugin": "${AGENT_WORK_ROOT}/app/definition/package/plugins/",
    "site.global.additional_config_properties": "['task.max-worker-threads=50', 'distributed-joins-enabled=true']",

    "site.global.catalog": "{'hive': ['connector.name=hive-cdh5','hive.metastore.uri=REDACTED','hive.allow-drop-table=true','hive.config.resources=REDACTED'],'tpch': ['connector.name=tpch']}",
    "site.global.jvm_args": "['-server', '-Xms40g', '-Xmx40g', '-XX:+UseG1GC', '-XX:G1HeapRegionSize=32M', '-XX:+UseGCOverheadLimit', '-XX:+ExplicitGCInvokesConcurrent', '-XX:+HeapDumpOnOutOfMemoryError', '-XX:OnOutOfMemoryError=kill -9 %p']",
    "application.def": ".slider/package/PRESTO_FLEX/presto-yarn-package-1.2-SNAPSHOT-0.147.zip",
    "java_home": "REDACTED"
  },
  "components": {
    "slider-appmaster": {
      "jvm.heapsize": "128M"
    }
  }
}
```

resources

```
{
  "schema": "http://example.org/specification/v2.0.0",
  "metadata": {
  },
  "global": {
    "yarn.container.failure.threshold" : "10",
    "yarn.container.failure.window.days" : "0",
    "yarn.container.failure.window.hours" : "1",
    "yarn.container.failure.window.minutes" : "0",
    "yarn.vcores": "2"
  },
  "components": {
    "slider-appmaster": {
    },
    "COORDINATOR": {
      "yarn.role.priority": "1",
      "yarn.component.instances": "1",
      "yarn.component.placement.policy": "1",
      "yarn.memory": "16384"
    },
    "WORKER": {
      "yarn.role.priority": "2",
      "yarn.component.instances": "50",
      "yarn.component.placement.policy": "1",
      "yarn.container.failure.threshold" : "15",
      "yarn.memory": "24576"
    }
  }
}
```

**Comment by mattsfuller** [comment]
Thanks for letting us know. We will take a look.

**Comment by anusudarsan** [comment]
@tglstory thanks for attaching the configuration files. Are you using slider-0.80? 

Also, did you find any errors in the slider.log for the outstanding requests, or it was just hung trying to fulfill the request?

**Comment by tglstory** [comment]
@kokosing @anusudarsan Here's the log.
[yarn.txt](https://github.com/prestodb/presto-yarn/files/358010/yarn.txt)

**Comment by anusudarsan** [comment]
@tglstory Looks like you are using slider-0.91, is that correct? Is there any specific reason for that? For presto-yarn we have tried and tested only slider-0.80.0. Have you tried slider-0.80 and experienced the same issue? 

We are planning to do a slider upgrade soon, but as of now the supported version is 0.80.0.

**Comment by tglstory** [comment]
@anusudarsan I tried .80 as well. Same issue. Seems like this is more of a slider issue rather than presto-yarn, but I was wondering if you guys could answer my question 1) above. Are you guys able to successfully stop and start, and all the workers come up?

**Comment by anusudarsan** [comment]
@tglstory destroy and re-create is only required if your slider configs have changed for the cluster, in other cases stop/start should work. We have never experienced any issues with restarting the application. We have tests for the scenario, but those are using a 4-node cluster. From your configuration, it looks like the issue happens in a cluster with 50+ workers? Did you ever got to reproduce it on a smaller cluster?

Also the YARN log you sent, is it from the slider-appmaster or from the worker nodes? I am assuming there is nothing interesting on the Presto worker logs (server.log) since the container request just hangs?

**Comment by tglstory** [comment]
@anusudarsan Thanks for the pointers. I fiddled around a lot and finally got a stable cluster working with stop/start support too. I appreciate the help! I find that most issues are on slider and not really much on you guys.

**Comment by anusudarsan** [comment]
@tglstory Glad that you got it working. Is there anything we can include in the documentation (troubleshooting) related to the fix you applied for the issue?

**Comment by tglstory** [comment]
If I can think of any, I'll submit a PR with the changes!

**Comment by anusudarsan** [comment]
Awesome. Thanks!
