### ISSUE TITLE
how to fixed the coordinator?

### ISSUE THREAD

**Issue by hereTac** [prestodb/presto-yarn#61]
if my yarn cluster use the labels , i will label the given node like 192.168.1.1 ,but if do not use labels ,use the conf like "site.global.coordinator_host": "${COORDINATOR_HOST}", it will use random node on yarn ,how to  appoint the node like 192.168.1.1? help. thks.@Anu Sudarsan

**Comment by kokosing** [comment]
To have coordinator be placed at specified node you need to use labels.

**Comment by hereTac** [comment]
@kokosing  .use labels ..is it the only way as u know?dude.

**Comment by kokosing** [comment]
yes. Please see https://slider.incubator.apache.org/docs/configuration/resources.html#placement (documentation of framework used by presto-yarn), to check if there is anything else which could help you. Notice that we presto yarn is using slider 0.80.

**Comment by hereTac** [comment]
@kokosing  i got it .thks a lot.
