### ISSUE TITLE
No support for resource groups ?

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto-yarn#77]
For installing presto on yarn based clusters. I do not see resource groups templates. is it not supported ?

**Comment by nakhanha** [comment]
@kokosing Can you please help ?

**Comment by kokosing** [comment]
I am afraid so. Any contribution is welcome.

CC: @anusudarsan

**Comment by nakhanha** [comment]
So the support for queues should be deprecated  ?

**Comment by kokosing** [comment]
What do you mean by `queues`? Query queues in Presto? These were removed from Presto in 0.198 (https://prestodb.io/docs/current/release/release-0.198.html). You should be using resource groups.

**Comment by nakhanha** [comment]
I mean, should presto-yarn support queues for backward compatibility, or should the support for query queues be dropped ?. asking If I were to contribute.

**Comment by kokosing** [comment]
Support for query queues should be dropped. Support for resource group should be added (if it isn't added already).

**Comment by nakhanha** [comment]
https://github.com/prestodb/presto-yarn/pull/78

cc: @kokosing @anusudarsan
