### ISSUE TITLE
Long create table queries are failing.

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto-yarn#80]
presto:default> create table txtnrecord1(txn INT, txndate STRING,custno INT, amount DOUBLE, category STRING, product STRING, city STRING, state STRING, spendby STRING) row format delimited fields terminated by ',' stored as textfile;
Query is gone (server restarted?)
presto:default> create table txtnrecord1(txn INT) row format delimited fields terminated by ',' stored as textfile;
Query is gone (server restarted?)
presto:default> create table txtnrecord1(txn INT) stored as textfile;
Query is gone (server restarted?)
presto:default> create table txtnrecord1(txn INT) ;
CREATE TABLE
presto:default> show tables

Is this known issue ?

cc: @kokosing

**Comment by kokosing** [comment]
No, it is not. Can you please look into Presto server logs and can you enable `--debug` in cli to see the actual error.

**Comment by nakhanha** [comment]
hive format is not supported.
