### ISSUE TITLE
presto not able to access jars in class path

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto-yarn#81]
@kokosing  @anusudarsan 

I want to add ADL file system support to presto.

I have copied all the relavant jars to the path mentioned below.
root@wn1-nkhadl:/mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538879153772_0002/container_1538879153772_0002_01_000002/app/install/presto-server-0.208/lib# ls -latr adl*
-rw-r--r-- 1 yarn hadoop 37618 Oct  7 02:01 adls2-oauth2-token-provider.jar

yarn     12168  5.2  2.8 27231744 824088 ?     Sl   02:44   3:57 java -cp /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538879153772_0002/container_1538879153772_0002_01_000002/app/install/presto-server-0.208/lib/* -server -Xmx23G -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -Dnode.data-dir=/var/lib/presto/data -Dnode.id=ed55b10e-c9da-11e8-bc16-000d3a913d9d -Dnode.environment=test -Dlog.levels-file=/var/lib/presto/etc/log.properties -Dplugin.config-dir=/var/lib/presto/etc/catalog -Dconfig=/var/lib/presto/etc/config.properties com.facebook.presto.server.PrestoServer

_0002_01_000002/app/install/presto-server-0.208/lib# jar tvf adls2-oauth2-token-provider.jar | grep HdiAdl
  1303 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdl.class
  9950 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdlFileSystem.class

when i submit the query
presto:default> create table txtn(txn1 INT);
Query 20181007_035559_00014_bg56u failed: Could not initialize class org.apache.hadoop.fs.adl.HdiAdlFileSystem

presto:default>

server.logs on cordinator show.
2018-10-07T02:50:27.202Z        INFO    query-scheduler-3       stderr  java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.fs.adl.HdiAdlFileSystem

is there something i am missing. please guide.

**Comment by nakhanha** [comment]
I have also added jars to connector path in hive-hadoop2

**Comment by nakhanha** [comment]
I can see that presto-server process
yarn     14311  0.0  0.0  11352  3100 ?        S    03:27   0:00 /bin/bash --login -c PATH=/usr/lib/jvm/java/bin:$PATH /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/container_1538967442733_0003_01_000003/app/install/presto-server-0.208/bin/launcher run --node-config /var/lib/presto/etc/node.properties --jvm-config /var/lib/presto/etc/jvm.config --config /var/lib/presto/etc/config.properties >> /var/lib/presto/data/var/log/server.log 2>&1
yarn     **14314**  9.1  2.7 27222468 802492 ?     Sl   03:27   1:25 java -cp /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/container_1538967442733_0003_01_000003/app/install/presto-server-0.208/lib/* -server -Xmx23G -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -Dcatalog.config-dir=/var/lib/presto/etc/catalog -Dnode.data-dir=/var/lib/presto/data -Dnode.id=266589cc-caaa-11e8-a432-000d3a3eac46 -Dnode.environment=test -Dlog.levels-file=/var/lib/presto/etc/log.properties -Dconfig=/var/lib/presto/etc/config.properties com.facebook.presto.server.PrestoServer

sshuser@wn1-nkhiap:~$ sudo lsof -p 14314 | grep 'jar' | grep 'adls2-oauth'                                                     presto-se 14314 yarn  mem       REG               8,17    37618 20448422 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/container_1538967442733_0003_01_000003/app/install/presto-server-0.208/plugin/hive-hadoop2/adls2-oauth2-token-provider.jar


and 

  `sshuser@wn1-nkhiap:~$` sudo jar tvf /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/conta                              iner_1538967442733_0003_01_000003/app/install/presto-server-0.208/plugin/hive-hadoop2/adls2-oauth2-token-provider.jar | grep 'H                              diAdl'
  1303 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdl.class
  9950 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdlFileSystem.class
`sshuser@wn1-nkhiap:~$`

**Comment by nakhanha** [comment]
@kokosing  Any inputs ?

**Comment by findepi** [comment]
closing in favor of @nakhanha 's https://github.com/prestodb/presto/issues/11656
